In [1]:
import numpy as np
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]


In [6]:
#syntax multidimention
c = np.arange(10) # range of value in array
d = np.linspace(1,5,6) # set of value by interval
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.8 2.6 3.4 4.2 5. ]


In [8]:
a = np.array([7,9,9,2])
b = np.array([(7,9,9,2),(16,11,9,6)])
print(a.ndim) #dimention of array
print(a.itemsize) # Byte size of each element
print(a.dtype) # datatype of array
print(a.size*a.itemsize) # MEMORY OCCUPIDE - SPACE OCCUPIDE
print(a.size) # NUMBER OF ELEMENTS OF ARRAY
print(b.shape) #shape of array

1
8
int64
32
4
(2, 4)


In [9]:
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b)
b = b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


In [11]:
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b[0,2]) #slicing the elements from certain row and certain column
print(b[0:,2]) #slicing elements from all rows and certain column

9
[9 9]


In [12]:
e = np.array([7,9,9,2,16,11,96])
print(e.min()) # minimum value
print(e.max()) #maximum value
print(e.sum()) #sum of value

2
96
150


In [14]:
a = np.array([7,9,9,2])
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis = 0)) # each element of first dim array with same index with another dim element
print(b.sum(axis = 1)) # sum of all elements in 1st dim and sum in 2nd dim
print(np.sqrt(a)) #sqrt of array element
print(np.std(a)) #
print(np.exp(a))
print(np.log(a))
print(np.log10(a))

[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [15]:
b = np.array([(7,9,9,2),(16,11,9,6)])
f = np.array([(1,2,3,4),(5,6,7,8)])
print(np.vstack((b,f))) #vertical stack
print(np.hstack((b,f))) #horizontal stack
print(b.ravel()) #merging as single

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
[ 7  9  9  2 16 11  9  6]


In [17]:
threeDarray = np.array([
    [[1,2,3],[4,5,6]],
    [[-1,-2,-3],[-4,-5,-6]]
])
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [24]:
for i in threeDarray.flatten():
     print(i)

1
2
3
4
5
6
-1
-2
-3
-4
-5
-6


In [25]:
threeDarray.flatten()
print(threeDarray)
threeDarray.ravel
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [29]:
##Filling array with specific value

In [30]:
#zeros
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [32]:
ones=np.ones(8)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [33]:
ones = ones.astype(int)
print(ones)

[1 1 1 1 1 1 1 1]


In [35]:
#arange
ranges = np.arange(5.6,9.8)

In [36]:
print(ranges)

[5.6 6.6 7.6 8.6 9.6]


In [37]:
#linaspace
linspace = np.linspace(3,6,100)
print(linspace)

[3.         3.03030303 3.06060606 3.09090909 3.12121212 3.15151515
 3.18181818 3.21212121 3.24242424 3.27272727 3.3030303  3.33333333
 3.36363636 3.39393939 3.42424242 3.45454545 3.48484848 3.51515152
 3.54545455 3.57575758 3.60606061 3.63636364 3.66666667 3.6969697
 3.72727273 3.75757576 3.78787879 3.81818182 3.84848485 3.87878788
 3.90909091 3.93939394 3.96969697 4.         4.03030303 4.06060606
 4.09090909 4.12121212 4.15151515 4.18181818 4.21212121 4.24242424
 4.27272727 4.3030303  4.33333333 4.36363636 4.39393939 4.42424242
 4.45454545 4.48484848 4.51515152 4.54545455 4.57575758 4.60606061
 4.63636364 4.66666667 4.6969697  4.72727273 4.75757576 4.78787879
 4.81818182 4.84848485 4.87878788 4.90909091 4.93939394 4.96969697
 5.         5.03030303 5.06060606 5.09090909 5.12121212 5.15151515
 5.18181818 5.21212121 5.24242424 5.27272727 5.3030303  5.33333333
 5.36363636 5.39393939 5.42424242 5.45454545 5.48484848 5.51515152
 5.54545455 5.57575758 5.60606061 5.63636364 5.66666667 5.69696

In [38]:
#scalar opration

In [39]:
matrix = np.array([[76,34,89],[23,34,45]])
print(matrix)

[[76 34 89]
 [23 34 45]]


In [40]:
print(matrix + 2)

[[78 36 91]
 [25 36 47]]


In [41]:
pythonlist = [[76,34,89],[23,34,45]]

In [42]:
print(pythonlist)

[[76, 34, 89], [23, 34, 45]]


In [43]:
print(matrix.T)

[[76 23]
 [34 34]
 [89 45]]


In [45]:
print(matrix[1,]) #first row

[23 34 45]


In [46]:
print("1-dimention")
full = np.full(10,5)
print(full)

print("2-dimention")
full = np.full((2,2),10)
print(full)

print("3-dimention")
full= np.full((2,5,4),5)
print(full)

1-dimention
[5 5 5 5 5 5 5 5 5 5]
2-dimention
[[10 10]
 [10 10]]
3-dimention
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [49]:
pythonlist1 = [[76,34,89],[23,34,45]]
pythonlist2 = [[76,34,89],[23,34,45]]

In [50]:
pythonlist1 + pythonlist2

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]

In [52]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[7,8,9],[10,11,12]])

In [54]:
print(matrix1 + matrix2)

[[ 8 10 12]
 [14 16 18]]


In [59]:
marks = np.array([
    [87,90,89],[100,87,90],
    [94,77,90],[100,86,98]
])

In [60]:
print(marks.min())
print(marks.max())
print(marks.sum())


77
100
1088


In [61]:
#axis =1 means eow    
print(marks.min(axis = 1))
print(marks.max(axis = 1))
print(marks.sum(axis = 1))
print(marks.min(axis = 1))
print(marks.std(axis = 1))

[87 87 77 86]
[ 90 100  94 100]
[266 277 261 284]
[87 87 77 86]
[1.24721913 5.55777733 7.25718035 6.18241233]


In [62]:
#append

In [64]:
x = np.array([
    [87,90,89],[100,87,90],
    [94,77,90],[100,86,98]
])

In [65]:
np.append(x,(2,3))

array([ 87,  90,  89, 100,  87,  90,  94,  77,  90, 100,  86,  98,   2,
         3])

In [66]:
new_array = np.array([1,2,3])


In [67]:
x = np.append ([[1,2,3],[4,5,6]],[[1,2,3],new_array],axis=0)
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3]])

In [68]:
x.ndim

2

In [69]:
np.transpose(x)

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [70]:
x.T

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [72]:
arr = np.array([
    [87,90,89],[100,87,90],
    [94,77,90],[100,86,98]
])

In [73]:
arr[arr>4]

array([ 87,  90,  89, 100,  87,  90,  94,  77,  90, 100,  86,  98])

In [74]:
array = np.arange(12)

In [75]:
array.shape = (3,4)

In [78]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [82]:
#save and load array

In [84]:
array = np.random.randint(10,20,(5,5))
np.save('array_file',array)

In [85]:
array2 = np.load('array_file.npy')
print(array2)

[[11 10 17 13 17]
 [12 18 16 18 11]
 [15 10 14 14 16]
 [17 19 11 15 12]
 [19 12 16 15 17]]
